# Generated by Django 4.0.6 on 2024-03-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0005_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='#FF7A00', max_length=7),
        ),
    ]
