# Generated by Django 4.0.6 on 2024-04-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0008_task_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
    ]
