# Generated by Django 4.0.6 on 2024-05-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0009_remove_subtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='join_backend.subtask'),
        ),
    ]
