# Generated by Django 4.0.6 on 2024-05-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0010_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inProgress', 'In Progress'), ('awaitFeedback', 'Await Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
